/**
 * Merge Accounting API
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RemoteData } from './remoteData';
import { ReportItem } from './reportItem';

/**
* # The BalanceSheet Object ### Description The `BalanceSheet` object is used to represent a company\'s balance sheet.  ### Usage Example Fetch from the `LIST BalanceSheets` endpoint and view a company\'s balance sheets.
*/
export class BalanceSheet {
    'id'?: string;
    /**
    * The third-party API ID of the matching object.
    */
    'remote_id'?: string | null;
    'remote_data'?: Array<RemoteData> | null;
    /**
    * The balance sheet\'s name.
    */
    'name'?: string | null;
    /**
    * The balance sheet\'s date.
    */
    'date'?: Date | null;
    /**
    * The balance sheet\'s net assets.
    */
    'net_assets'?: number | null;
    'assets'?: Array<ReportItem>;
    'liabilities'?: Array<ReportItem>;
    'equity'?: Array<ReportItem>;
    /**
    * The balance sheet\'s periods.
    */
    'periods'?: Array<Date> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "remote_id",
            "baseName": "remote_id",
            "type": "string"
        },
        {
            "name": "remote_data",
            "baseName": "remote_data",
            "type": "Array<RemoteData>"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "Date"
        },
        {
            "name": "net_assets",
            "baseName": "net_assets",
            "type": "number"
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<ReportItem>"
        },
        {
            "name": "liabilities",
            "baseName": "liabilities",
            "type": "Array<ReportItem>"
        },
        {
            "name": "equity",
            "baseName": "equity",
            "type": "Array<ReportItem>"
        },
        {
            "name": "periods",
            "baseName": "periods",
            "type": "Array<Date>"
        }    ];

    static getAttributeTypeMap() {
        return BalanceSheet.attributeTypeMap;
    }
}

