/**
 * Merge Accounting API
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RemoteData } from './remoteData';
import { ReportItem } from './reportItem';

/**
* # The CashFlowStatement Object ### Description The `CashFlowStatement` object is used to represent a company\'s cash flow statement.  ### Usage Example Fetch from the `LIST CashFlowStatements` endpoint and view a company\'s cash flow statements.
*/
export class CashFlowStatement {
    'id'?: string;
    /**
    * The third-party API ID of the matching object.
    */
    'remote_id'?: string | null;
    'remote_data'?: Array<RemoteData> | null;
    /**
    * The cash flow statement\'s name.
    */
    'name'?: string | null;
    /**
    * The cash flow statement\'s start date.
    */
    'start_date'?: Date | null;
    /**
    * The cash flow statement\'s end date.
    */
    'end_date'?: Date | null;
    'operating_activities'?: Array<ReportItem>;
    'investing_activities'?: Array<ReportItem>;
    'financing_activities'?: Array<ReportItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "remote_id",
            "baseName": "remote_id",
            "type": "string"
        },
        {
            "name": "remote_data",
            "baseName": "remote_data",
            "type": "Array<RemoteData>"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "start_date",
            "baseName": "start_date",
            "type": "Date"
        },
        {
            "name": "end_date",
            "baseName": "end_date",
            "type": "Date"
        },
        {
            "name": "operating_activities",
            "baseName": "operating_activities",
            "type": "Array<ReportItem>"
        },
        {
            "name": "investing_activities",
            "baseName": "investing_activities",
            "type": "Array<ReportItem>"
        },
        {
            "name": "financing_activities",
            "baseName": "financing_activities",
            "type": "Array<ReportItem>"
        }    ];

    static getAttributeTypeMap() {
        return CashFlowStatement.attributeTypeMap;
    }
}

