/**
 * Merge Accounting API
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RemoteData } from './remoteData';
import { ReportItem } from './reportItem';

/**
* # The ProfitAndLoss Object ### Description The `ProfitAndLoss` object is used to represent a company\'s Profit and Loss reports.  ### Usage Example Fetch from the `GET ProfitAndLoss` endpoint and view a company\'s Profit and Loss report.
*/
export class ProfitAndLoss {
    'id'?: string;
    /**
    * The third-party API ID of the matching object.
    */
    'remote_id'?: string | null;
    'remote_data'?: Array<RemoteData> | null;
    /**
    * The profit and loss report\'s name.
    */
    'name'?: string | null;
    /**
    * The profit and loss report\'s start date.
    */
    'start_date'?: Date | null;
    /**
    * The profit and loss report\'s end date.
    */
    'end_date'?: Date | null;
    'income'?: Array<ReportItem>;
    'cost_of_sales'?: Array<ReportItem>;
    /**
    * The profit and loss report\'s gross profit.
    */
    'gross_profit'?: number | null;
    'expenses'?: Array<ReportItem>;
    /**
    * The profit and loss report\'s net operating profit.
    */
    'net_operating_profit'?: number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "remote_id",
            "baseName": "remote_id",
            "type": "string"
        },
        {
            "name": "remote_data",
            "baseName": "remote_data",
            "type": "Array<RemoteData>"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "start_date",
            "baseName": "start_date",
            "type": "Date"
        },
        {
            "name": "end_date",
            "baseName": "end_date",
            "type": "Date"
        },
        {
            "name": "income",
            "baseName": "income",
            "type": "Array<ReportItem>"
        },
        {
            "name": "cost_of_sales",
            "baseName": "cost_of_sales",
            "type": "Array<ReportItem>"
        },
        {
            "name": "gross_profit",
            "baseName": "gross_profit",
            "type": "number"
        },
        {
            "name": "expenses",
            "baseName": "expenses",
            "type": "Array<ReportItem>"
        },
        {
            "name": "net_operating_profit",
            "baseName": "net_operating_profit",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ProfitAndLoss.attributeTypeMap;
    }
}

