/**
 * Merge Accounting API
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CurrencyEnum } from './currencyEnum';
import { VendorCreditLine } from './vendorCreditLine';

/**
* # The VendorCredit Object ### Description The `VendorCredit` object is used to represent a company\'s vendor credits.  ### Usage Example Fetch from the `GET VendorCredit` endpoint and view a company\'s vendor credits.
*/
export class VendorCredit {
    'id'?: string;
    /**
    * The third-party API ID of the matching object.
    */
    'remote_id'?: string | null;
    /**
    * The vendor credit\'s number.
    */
    'number'?: string | null;
    /**
    * The vendor credit\'s transaction date.
    */
    'transaction_date'?: Date | null;
    'vendor'?: string | null;
    /**
    * The vendor credit\'s total amount.
    */
    'total_amount'?: number | null;
    /**
    * The vendor credit\'s currency.
    */
    'currency'?: CurrencyEnum | null;
    'lines'?: Array<VendorCreditLine>;
    /**
    * Indicates whether or not this object has been deleted on the third-party.
    */
    'remote_was_deleted'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "remote_id",
            "baseName": "remote_id",
            "type": "string"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string"
        },
        {
            "name": "transaction_date",
            "baseName": "transaction_date",
            "type": "Date"
        },
        {
            "name": "vendor",
            "baseName": "vendor",
            "type": "string"
        },
        {
            "name": "total_amount",
            "baseName": "total_amount",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "CurrencyEnum"
        },
        {
            "name": "lines",
            "baseName": "lines",
            "type": "Array<VendorCreditLine>"
        },
        {
            "name": "remote_was_deleted",
            "baseName": "remote_was_deleted",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return VendorCredit.attributeTypeMap;
    }
}

